Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManager.Services;
using TaskManager.Common.Mvc;
using TaskManager.Entity;
using System.Web.Security;
using TaskManager.Common.Exceptions;
using TaskManager.Common.Utils;
namespace Web.Controllers
{
    public class HomeController : BaseController
    {
        private SystemService _sysService = new SystemService();
        private TaskService _taskService = new TaskService();
        [MyAuthorize]
        public ActionResult Index()
        {
            return View();
        } 
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult NoRight() {
            return View();
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Login");
        }
        [HttpPost]
        public ActionResult Login(string UserName, string PassWord)
        {
            JsonReturnMessages msg = new JsonReturnMessages();
            try
            {
                IdentityUser user = _sysService.UserAuth(UserName, PassWord);
            MyContext.CurrentUser = user;
                msg.IsSuccess = true;
            //FormsAuthentication.SetAuthCookie(user.UserId.ToLower(), false);
            FormsAuthentication.SetAuthCookie(Newtonsoft.Json.JsonConvert.SerializeObject( user),true);
            }
            catch (BOException ex)
            {
                msg.Data = ex.ErrorCode;
                msg.Msg = ex.Message;
            }
            catch (Exception ex)
            {
                msg.Data = "ERROR";
                msg.Msg = ex.Message;

            }

            return Json(msg);

        }
        [MyAuthorize]
        public ActionResult RestTask()
        {
            _taskService.RestAll();
            return Content("重启成功");
        }
       
    }
}

Web/Controllers/ServerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManager.Services;
using TaskManager.Entity;
using TaskManager.Entity.Filter;
using TaskManager.Common.Mvc;

namespace TaskManager.Web.Controllers
{
    [MyAuthorize]
    public class ServerController : BaseController
    {
        private ServerService _serverService = new ServerService();
        // GET: Task
        public ActionResult ServerList()
        {
            return View();
        }
        [HttpPost]
        public JsonResult ServerList(int Status=-1)
        {
            var list = _serverService.GetAllServer();
            PageList<Ts_Servers> pageList = new PageList<Ts_Servers>() { DataList = list };
            return Json(pageList);
        }
    }
}

Web/Controllers/SystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManager.Services;
using TaskManager.Entity;
using TaskManager.Entity.Filter;
using TaskManager.Common.Mvc;

namespace TaskManager.Web.Controllers
{
    [MyAuthorize]
    public class SystemController: BaseController
    {
        private SystemService _syskService = new SystemService();
        // GET: Task
        [AdminAuthorize]
        public ActionResult UserList()
        {
            return View();
        }
        [AdminAuthorize]
        [HttpPost]
        public JsonResult UserList(int Status=-1)
        { 
            var list= _syskService.GetAllUser(Status);
            PageList<Tu_Users> pageList = new PageList<Tu_Users>() { DataList = list };
            return Json(pageList);
        }
        [AdminAuthorize]
        public ActionResult UserEdit(int UserId)
        { 
            List<SelectListItem> StatusList = new List<SelectListItem>();
            foreach (int item in Enum.GetValues(typeof(StatusEnum)))
            {
                StatusList.Add(new SelectListItem() { Value = item.ToString(), Text = Enum.GetName(typeof(StatusEnum), item) });
            }
            ViewBag.StatusList = StatusList;
            Tu_Users user = _syskService.GetUserInfo(UserId);
            return View("UserEdit", user);
        }
        [AdminAuthorize]
        public ActionResult DeleteUser(int UserId)
        {
            JsonReturnMessages msg = new JsonReturnMessages();
            msg.IsSuccess = _syskService.DeleteUser(UserId);
            return Json(msg);
        }
        [AdminAuthorize]
        public ActionResult UserAdd()
        { 

            List<SelectListItem> StatusList = new List<SelectListItem>();
            foreach (int item in Enum.GetValues(typeof(StatusEnum)))
            {
                StatusList.Add(new SelectListItem() { Value = item.ToString(), Text = Enum.GetName(typeof(StatusEnum), item) });
            }
            ViewBag.StatusList = StatusList;
            Tu_Users user = new Tu_Users(); 
            return View("UserEdit", user);
        }
        [AdminAuthorize]
        [HttpPost]
        public ActionResult SaveUser(Tu_Users user) { 
            JsonReturnMessages msg = new JsonReturnMessages();
           msg.IsSuccess= _syskService.SaveUser(user);
            return Json(msg);
        }
    }
}

Web/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManager.Services;
using TaskManager.Entity;
using TaskManager.Entity.Filter;
using TaskManager.Common.Mvc;
using TaskManager.Common.Exceptions;
using TaskManager.Tasks;
using TaskManager.Common.Corn;

namespace TaskManager.Web.Controllers
{
    [MyAuthorize]
    public class TaskController : BaseController
    {
        private TaskService _taskService = new TaskService();
        // GET: Task
        public ActionResult TaskList()
        {
            ViewBag.IsAdmin = IsAdmin;        
            return View();
        }
        [HttpPost]
        public JsonResult TaskList(int Status=-1)
        {
            var list=_taskService.GetTaskList(Status);
            PageList<ModelTaskList> pageList = new PageList<ModelTaskList>() { DataList = list };
            return Json(pageList);
        }
        public ActionResult TaskLogs(string TaskGuid)
        {
            ViewBag.TaskGuid = TaskGuid;
            return View();
        }
        [HttpPost]
        public JsonResult TaskLogs(TaskLogFilter filter,PageView pageView)
        {
            var list = _taskService.GetAllTaskLog(filter,pageView);
            foreach (var item in list.DataList)
            {
                item.ExecResult = Server.HtmlEncode(item.ExecResult);
            }
            return Json(list);
        }
        public ActionResult TaskEdit(string TaskGuid)
        {
            InitTask();
            Ts_Tasks tasks = _taskService.GetTaskByGuid(TaskGuid);
            return View("TaskEdit", tasks);
        }
        private void InitTask() {
            List<SelectListItem> ExecTypeList = new List<SelectListItem>();
            foreach (int item in Enum.GetValues(typeof(ExecTypeEnum)))
            {
                ExecTypeList.Add(new SelectListItem() { Value = item.ToString(), Text = Enum.GetName(typeof(ExecTypeEnum), item) });
            }
            ViewBag.ExecTypeList = ExecTypeList;
            List<SelectListItem> StatusList = new List<SelectListItem>();
            foreach (int item in Enum.GetValues(typeof(StatusEnum)))
            {
                StatusList.Add(new SelectListItem() { Value = item.ToString(), Text = Enum.GetName(typeof(StatusEnum), item) });
            }
            ViewBag.StatusList = StatusList;
            List<SelectListItem> ExecMethodList = new List<SelectListItem>();
            foreach (var item in Enum.GetNames(typeof(ExecMethodEnum)))
            {
                ExecMethodList.Add(new SelectListItem() { Value = item, Text = item });
            }
            ExecMethodList.Add(new SelectListItem() { Value = "", Text = "请选择" });
            ViewBag.ExecMethodList = ExecMethodList;

        }
        public ActionResult TaskAdd()
        {
            InitTask();

            Ts_Tasks tasks = new Ts_Tasks();
            tasks.TimeOut = 30;
            tasks.RunServerId = _taskService.GetNewRunServerId();
           // tasks.ExecMethod = "GET";
            return View("TaskEdit", tasks);
        }
        [HttpPost]
        public ActionResult SaveTask(Ts_Tasks tasks) {
            JsonReturnMessages msg = new JsonReturnMessages();
            try
            {
                msg.IsSuccess = _taskService.SaveTask(tasks);
                _taskService.RestTask(tasks);
            }
            catch (BOException ex) {
                msg.Msg = ex.Message;
            }
            return Json(msg);
        }
        [HttpPost]
        public ActionResult RunTask(string TaskGuid)
        {
            JsonReturnMessages msg = new JsonReturnMessages();
            try
            {
                msg.IsSuccess = _taskService.RunTask(TaskGuid);
            }
            catch (Exception ex) {
                msg.Msg = ex.Message;
            }
            return Json(msg);
        }
        [AdminAuthorize]
        [HttpPost]
        public ActionResult RemoveTask(string TaskGuid)
        {
            JsonReturnMessages msg = new JsonReturnMessages();
            try
            {
              _taskService.RemoveTask(TaskGuid);
                msg.IsSuccess = true;
            }
            catch (BOException ex)
            {
                msg.Msg = ex.Message;
            }
            return Json(msg);
        }
        [HttpPost]
        public ActionResult QueryNextTime(string Interval)
        {
            JsonReturnMessages msg = new JsonReturnMessages();
            try
            {
                msg.IsSuccess = true;
                CronExpression expression = new CronExpression(Interval);
                List<string> nextTimeList = new List<string>();
                DateTimeOffset now = DateTimeOffset.Now;
                for (int i = 0; i < 10; i++)
                {
                    var lastOffset = expression.GetNextValidTimeAfter(now);
                    if (lastOffset != null)
                    {
                        now = lastOffset.Value;
                        nextTimeList.Add(lastOffset.Value.LocalDateTime.ToString());
                    }
                }
                msg.Data = nextTimeList;
            }
            catch (Exception ex)
            {
                msg.Msg = "cron表达式错误";
            }
            return Json(msg);
        }
    }
}

Web/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <script src="~/Scripts/jquery-1.12.3.min.js"></script>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/common.js"></script>
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/index.css" rel="stylesheet" />
</head>
<body>
   
    <div class="navbar navbar-duomi navbar-static-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/Home/index" id="logo">
                    任务管理系统
                </a>
                <a href="/Home/LogOut">退出</a>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <ul id="main-nav" class="nav nav-tabs nav-stacked" style="">
                    <li class="active">
                        <a href="#">
                            <i class="glyphicon glyphicon-th-large"></i>
                            首页
                        </a>
                    </li>
                    <li>
                        <a href="#taskSetting" class="nav-header collapsed" data-toggle="collapse">
                            <i class="glyphicon glyphicon-cog"></i>
                            任务管理
                            <span class="pull-right glyphicon glyphicon-chevron-down"></span>
                        </a>
                        <ul id="taskSetting" class="nav nav-list collapse secondmenu" style="height: 0px;">
                            <li><a target="main" href="@Url.Action("TaskList","Task")"><i class="glyphicon glyphicon-user"></i>任务列表</a></li>
                            <li><a target="main" href="@Url.Action("ServerList","Server")"><i class="glyphicon glyphicon-user"></i>服务器列表</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#systemSetting" class="nav-header collapsed" data-toggle="collapse">
                            <i class="glyphicon glyphicon-cog"></i>
                            系统管理
                            <span class="pull-right glyphicon glyphicon-chevron-down"></span>
                        </a>
                        <ul id="systemSetting" class="nav nav-list collapse secondmenu" style="height: 0px;">
                            <li><a target="main" href="@Url.Action("UserList","System")"><i class="glyphicon glyphicon-user"></i>用户列表</a></li>
                            
                        </ul>
                    </li>


                </ul>
            </div>
            <div class="col-md-10">
                <iframe src="" id="main" name="main"  height="900px" style="border:none;overflow-x:auto;width:100%"></iframe>
            </div>
        </div>
    </div>
</body>
</html>

Web/Views/Home/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <script src="~/Scripts/jquery-1.12.3.min.js"></script>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" /> 
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/common.js"></script>
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/common.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="signin">
            <div class="signin-box">
                <h2>
                    欢迎登录 
                </h2><hr />
                    <div class="form-group row">
                        <label class="col-sm-2 control-label" for="username">用户名</label><div class="col-sm-4">
                            <input id="txtUserName" type="text" class="col-sm-2 form-control" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 control-label" for="passwd">密码</label><div class="col-sm-4">
                            <input id="txtPassWord" type="password" class="col-sm-2 form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2"></div><div class="col-sm-2">
                            <input type="button" value="登 入" id="btnLogin" class="btn btn-primary col-sm-2 form-control" />
                        </div>
                    </div>
                
            </div>
        </div>
    </div>



    
    
    <script type="text/javascript">
        $(document).ready(function () {


        
            $("#btnLogin").click(function (e) {

                var username = $("#txtUserName").val();
                var password = $("#txtPassWord").val();
                $.post('@Url.Action("Login")', { UserName: username,PassWord:password },
                      function (res) {
                          if (res.IsSuccess) {
                              alert("登录成功");
                              document.location.href = '@Url.Action("Index","Home")';
                          }
                          else {
                              alert(res.Msg);
                          }
                      },
                      "json"
                );
            });
        });
    </script>
</body>
</html>

Web/Views/Home/NoRight.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>NoRight</title>
</head>
<body>
    <div>
        没有权限！
    </div>
</body>
</html>